### ISSUE TITLE
WSL Make Gives Errors

### ISSUE THREAD

**Issue by finnaminope** [prochazkaml/MichalOS#14]
I Get These Errors When Running Make:

misc/compress content/atomino.dro content/atomino.drz
make: misc/compress: Permission denied
make: *** [Makefile:47: content/atomino.drz] Error 127

Already Tried Everything And Installed Deps

**Comment by finnaminope** [comment]
Sorry For The Bad Formatting

**Comment by shoaib-jamal** [comment]
Run the make command with appropriate permissions: You can try running the make command with elevated privileges. Such as the sudo command before the make command, like this: sudo make.

**Comment by prochazkaml** [comment]
Try running `chmod +x misc/compress`, seems like you do not have permission to execute the compress program. Please, for the love of God, do **not** run make as sudo!

**Comment by prochazkaml** [comment]
Also, are you sure you have the latest version of the repo? In the latest Makefile, I am not referencing "misc/compress" at all.

(On the other hand, I understand, as the latest commit is probably broken, as I tried to make the API more stable back in January and never finished, leaving it in a half-broken state...)
