### ISSUE TITLE
MichalOS on a luggable 386

### ISSUE THREAD

**Issue by incanus** [prochazkaml/MichalOS#9]
_(Crossposting [from SourceForge](https://sourceforge.net/p/michalos/discussion/general/thread/7aaf8f40d8/#f39f))_

If you're curious, I recently discovered MichalOS (as well as MikeOS) and got both running on a circa-1989 386 luggable! Pretty fun. I'm recently getting back into old systems & their BASICs, as well as newly into electronics, so I'm starting to meet in the middle with old assembly code and lower-level stuff after a career of higher-level programming. Very fun. Thanks for this project. 

![IMG_5638](https://user-images.githubusercontent.com/17722/115485707-17f16200-a20a-11eb-8e22-6b226689b771.JPG)

![IMG_5639](https://user-images.githubusercontent.com/17722/115485717-1aec5280-a20a-11eb-8438-95ecfe4deb62.JPG)

**Comment by prochazkaml** [comment]
This looks absolutely amazing, I hope you have a lot of fun with it!

Of course, if you find any issue or bug running MichalOS on that machine, please do let me know.
